"""initial domain tables

Revision ID: 5ebf3e8d0a3e
Revises: 
Create Date: 2026-08-04 18:34:48.288394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebf3e8d0a3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_lat', sa.String(length=32), nullable=False),
    sa.Column('start_lng', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('dogs',
    sa.Column('dog_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='dogsize'), nullable=False),
    sa.Column('kakao_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('dog_id')
    )
    op.create_index(op.f('ix_dogs_kakao_id'), 'dogs', ['kakao_id'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lat', sa.String(length=32), nullable=False),
    sa.Column('lng', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('likes',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'dog_id')
    )
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('diary', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('places',
    sa.Column('place_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PARK', 'CAFE', 'RESTAURANT', 'HOSPITAL', 'PET_SHOP', 'ETC', name='placecategory'), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('open_time', sa.String(length=100), nullable=True),
    sa.Column('rest_day', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('place_id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('saves',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'dog_id')
    )
    op.create_table('course_place',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stay_minutes', sa.Integer(), nullable=False),
    sa.Column('travel_time', sa.Integer(), nullable=True),
    sa.Column('travel_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'place_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_place')
    op.drop_table('saves')
    op.drop_table('places')
    op.drop_table('logs')
    op.drop_table('likes')
    op.drop_table('locations')
    op.drop_index(op.f('ix_dogs_kakao_id'), table_name='dogs')
    op.drop_table('dogs')
    op.drop_table('courses')
    # ### end Alembic commands ###
