"""initial schema

Revision ID: a3b13a1e82b4
Revises: 
Create Date: 2026-09-15 17:08:14.235717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b13a1e82b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('dog_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kakao_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='dog_size'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('dog_id')
    )
    op.create_index(op.f('ix_dogs_kakao_id'), 'dogs', ['kakao_id'], unique=True)
    op.create_table('places',
    sa.Column('place_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PARK', 'CAFE', 'RESTAURANT', 'HOSPITAL', 'PET_SHOP', 'ETC', name='place_category'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('rest_day', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index(op.f('ix_places_content_id'), 'places', ['content_id'], unique=True)
    op.create_table('courses',
    sa.Column('course_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('dog_id', sa.BigInteger(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('walk_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_courses_dog_id'), 'courses', ['dog_id'], unique=False)
    op.create_table('course_places',
    sa.Column('course_place_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stay_minutes', sa.Integer(), nullable=True),
    sa.Column('travel_minutes', sa.Integer(), nullable=True),
    sa.Column('travel_distance_meters', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('course_place_id'),
    sa.UniqueConstraint('course_id', 'sequence', name='uq_course_places_course_sequence')
    )
    op.create_index(op.f('ix_course_places_course_id'), 'course_places', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_places_place_id'), 'course_places', ['place_id'], unique=False)
    op.create_table('likes',
    sa.Column('like_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('dog_id', 'course_id', name='uq_likes_dog_course')
    )
    op.create_index(op.f('ix_likes_course_id'), 'likes', ['course_id'], unique=False)
    op.create_index(op.f('ix_likes_dog_id'), 'likes', ['dog_id'], unique=False)
    op.create_table('logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_logs_course_id'), 'logs', ['course_id'], unique=False)
    op.create_index(op.f('ix_logs_dog_id'), 'logs', ['dog_id'], unique=False)
    op.create_table('saves',
    sa.Column('save_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dog_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('save_id'),
    sa.UniqueConstraint('dog_id', 'course_id', name='uq_saves_dog_course')
    )
    op.create_index(op.f('ix_saves_course_id'), 'saves', ['course_id'], unique=False)
    op.create_index(op.f('ix_saves_dog_id'), 'saves', ['dog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    MySQL(InnoDB)은 FK 제약이 참조하는 인덱스를 먼저 지우면 에러(1553)가 나므로,
    autogenerate가 만든 개별 drop_index 호출은 다 지우고 drop_table만 남긴다 —
    테이블을 지우면 그 테이블의 인덱스/FK도 함께 정리된다. 순서는 FK 참조 방향의
    역순(자식 → 부모)이라 그대로 둔다.
    """
    op.drop_table('saves')
    op.drop_table('logs')
    op.drop_table('likes')
    op.drop_table('course_places')
    op.drop_table('courses')
    op.drop_table('places')
    op.drop_table('dogs')
